// GENERATED by scripts/gen-api-index.mjs — do not edit.
// Regenerate with `npm run gen:api`; `npm run deploy:pages` does it for you.
// Source of truth: the library's runtime exports + src/vocabulary.js.

export type ApiIndexEntry = {
  namespace: string;
  group: string;
  name: string;
  qualified: string;
  call: string;
  own: string[];
  universal: string[];
  docs: string | null;
};

export type ApiNamespace = { namespace: string; blurb: string; count: number };

export const API_LIBRARY_VERSION = "0.1.0-alpha.1";
export const API_GENERATED_AT = "2026-09-22T06:00:07.788Z";
export const API_NAMESPACES: ApiNamespace[] = [
  {
    "namespace": "plot",
    "blurb": "Marks draw the rows of your dataset.",
    "count": 50
  },
  {
    "namespace": "elements",
    "blurb": "Chart elements draw a scale: axes, grids and legends.",
    "count": 11
  },
  {
    "namespace": "edit",
    "blurb": "Edits map a gesture back through a scale to write a column.",
    "count": 52
  },
  {
    "namespace": "constraints",
    "blurb": "Constraints are rules over the dataset. Each one rejects or repairs every edit.",
    "count": 9
  },
  {
    "namespace": "guides",
    "blurb": "Guides draw reference lines and interaction state. They never write data.",
    "count": 10
  },
  {
    "namespace": "widgets",
    "blurb": "Widgets are complete survey instruments. Each returns a spec.",
    "count": 13
  },
  {
    "namespace": "format",
    "blurb": "Formatters turn a value into a string for a label or an axis.",
    "count": 7
  }
];
export const API_TOP_LEVEL = [
  {
    "name": "CanvasRenderer",
    "kind": "function",
    "docs": null
  },
  {
    "name": "D3Renderer",
    "kind": "function",
    "docs": null
  },
  {
    "name": "DEFAULT_THEME",
    "kind": "object",
    "docs": null
  },
  {
    "name": "Elicit",
    "kind": "function",
    "docs": "/overview"
  },
  {
    "name": "resolveTheme",
    "kind": "function",
    "docs": null
  },
  {
    "name": "setTheme",
    "kind": "function",
    "docs": "/theming"
  },
  {
    "name": "setWarnings",
    "kind": "function",
    "docs": null
  },
  {
    "name": "themes",
    "kind": "object",
    "docs": "/theming"
  }
];
export const API_INDEX: ApiIndexEntry[] = [
  {
    "namespace": "plot",
    "group": "plot",
    "name": "arc",
    "qualified": "plot.arc",
    "call": "plot.arc(options)",
    "own": [
      "outerRadius",
      "innerRadius",
      "padAngle",
      "arc",
      "start",
      "end",
      "handles",
      "handleSize",
      "handleColor"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/arc"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "area",
    "qualified": "plot.area",
    "call": "plot.area(options)",
    "own": [
      "orientation",
      "curve",
      "handles",
      "handleSize",
      "handleColor",
      "connect"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/area"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "areaX",
    "qualified": "plot.areaX",
    "call": "plot.areaX(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/area"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "areaY",
    "qualified": "plot.areaY",
    "call": "plot.areaY(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/area"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "bar",
    "qualified": "plot.bar",
    "call": "plot.bar(options)",
    "own": [
      "orientation",
      "stack",
      "handles",
      "handleSize",
      "handleColor"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/bar"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "barX",
    "qualified": "plot.barX",
    "call": "plot.barX(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/bar"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "barY",
    "qualified": "plot.barY",
    "call": "plot.barY(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/bar"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "composite",
    "qualified": "plot.composite",
    "call": "plot.composite(options)",
    "own": [
      "parts",
      "discreteScale"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/composite"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "curve",
    "qualified": "plot.curve",
    "call": "plot.curve(options)",
    "own": [
      "orientation",
      "length"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/curve"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "curveX",
    "qualified": "plot.curveX",
    "call": "plot.curveX(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/curve"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "curveY",
    "qualified": "plot.curveY",
    "call": "plot.curveY(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/curve"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "donut",
    "qualified": "plot.donut",
    "call": "plot.donut(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/arc"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "dotStack",
    "qualified": "plot.dotStack",
    "call": "plot.dotStack(options)",
    "own": [
      "orientation",
      "gap",
      "ghost",
      "label"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/dotstack"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "dotStackX",
    "qualified": "plot.dotStackX",
    "call": "plot.dotStackX(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/dotstack"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "dotStackY",
    "qualified": "plot.dotStackY",
    "call": "plot.dotStackY(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/dotstack"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "ellipse",
    "qualified": "plot.ellipse",
    "call": "plot.ellipse(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/ellipse"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "face",
    "qualified": "plot.face",
    "call": "plot.face(options)",
    "own": [
      "ink"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/face"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "geoBasemap",
    "qualified": "plot.geoBasemap",
    "call": "plot.geoBasemap(options)",
    "own": [
      "geojson",
      "stroke",
      "strokeWidth",
      "fill"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/geo"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "geoLine",
    "qualified": "plot.geoLine",
    "call": "plot.geoLine(options)",
    "own": [
      "curve",
      "handles",
      "handleSize",
      "handleColor",
      "connect",
      "showVertices"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/geo"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "geoPoint",
    "qualified": "plot.geoPoint",
    "call": "plot.geoPoint(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/geo"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "geoPolygon",
    "qualified": "plot.geoPolygon",
    "call": "plot.geoPolygon(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/geo"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "geoRect",
    "qualified": "plot.geoRect",
    "call": "plot.geoRect(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/geo"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "geoText",
    "qualified": "plot.geoText",
    "call": "plot.geoText(options)",
    "own": [
      "format"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/geo"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "geoTile",
    "qualified": "plot.geoTile",
    "call": "plot.geoTile(options)",
    "own": [
      "url",
      "subdomains",
      "tileSize",
      "minZoom",
      "maxZoom",
      "zoomOffset",
      "attribution",
      "attributionSize",
      "opacity"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/geo"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "line",
    "qualified": "plot.line",
    "call": "plot.line(options)",
    "own": [
      "orientation",
      "curve",
      "handles",
      "handleSize",
      "handleColor",
      "connect"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/line"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "lineX",
    "qualified": "plot.lineX",
    "call": "plot.lineX(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/line"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "lineY",
    "qualified": "plot.lineY",
    "call": "plot.lineY(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/line"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "link",
    "qualified": "plot.link",
    "call": "plot.link(options)",
    "own": [
      "curve",
      "curvature",
      "spread",
      "arrow",
      "arrowSize",
      "inset",
      "sourceInset",
      "targetInset",
      "loopRadius",
      "format",
      "labelBackground",
      "labelPadding",
      "labelRadius",
      "labelOpacity",
      "nodeWidth",
      "nodeHeight",
      "cornerRadius",
      "sourceSide",
      "targetSide",
      "handles",
      "handleSize",
      "handleColor"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/network"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "needle",
    "qualified": "plot.needle",
    "call": "plot.needle(options)",
    "own": [
      "length",
      "handles",
      "handleSize",
      "handleColor",
      "baseWidth"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/needle"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "node",
    "qualified": "plot.node",
    "call": "plot.node(options)",
    "own": [
      "dy",
      "shape",
      "format"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/network"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "path",
    "qualified": "plot.path",
    "call": "plot.path(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/line"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "point",
    "qualified": "plot.point",
    "call": "plot.point(options)",
    "own": [
      "shape"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/point"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "rect",
    "qualified": "plot.rect",
    "call": "plot.rect(options)",
    "own": [
      "orientation",
      "width",
      "height",
      "rx"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/rect"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "rectX",
    "qualified": "plot.rectX",
    "call": "plot.rectX(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/rect"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "rectY",
    "qualified": "plot.rectY",
    "call": "plot.rectY(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/rect"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "rule",
    "qualified": "plot.rule",
    "call": "plot.rule(options)",
    "own": [
      "orientation",
      "strokeDasharray",
      "discreteScale"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/axes"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "ruleX",
    "qualified": "plot.ruleX",
    "call": "plot.ruleX(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/axes"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "ruleY",
    "qualified": "plot.ruleY",
    "call": "plot.ruleY(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/axes"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "sticker",
    "qualified": "plot.sticker",
    "call": "plot.sticker(options)",
    "own": [
      "padding",
      "radius",
      "maxWidth",
      "minWidth",
      "minHeight",
      "lineHeight",
      "fontFamily",
      "format"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/sticker"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "text",
    "qualified": "plot.text",
    "call": "plot.text(options)",
    "own": [
      "orientation",
      "format",
      "wrap",
      "lineHeight"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/text"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "textX",
    "qualified": "plot.textX",
    "call": "plot.textX(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/text"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "textY",
    "qualified": "plot.textY",
    "call": "plot.textY(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/text"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "tick",
    "qualified": "plot.tick",
    "call": "plot.tick(options)",
    "own": [
      "orientation",
      "inset",
      "length"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/tick"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "tickX",
    "qualified": "plot.tickX",
    "call": "plot.tickX(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/tick"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "tickY",
    "qualified": "plot.tickY",
    "call": "plot.tickY(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/tick"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "trend",
    "qualified": "plot.trend",
    "call": "plot.trend(options)",
    "own": [
      "anchor",
      "probe",
      "grip",
      "handles",
      "handleSize",
      "handleColor"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/trend"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "trendBand",
    "qualified": "plot.trendBand",
    "call": "plot.trendBand(options)",
    "own": [
      "render",
      "levels",
      "samples",
      "seed",
      "sigma",
      "distribution",
      "anchor",
      "probe",
      "grip",
      "handles",
      "handleSize",
      "handleColor"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/trend"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "waffle",
    "qualified": "plot.waffle",
    "call": "plot.waffle(options)",
    "own": [
      "orientation",
      "unit",
      "multiple",
      "gap",
      "shape",
      "showEmpty",
      "emptyFill"
    ],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/waffle"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "waffleX",
    "qualified": "plot.waffleX",
    "call": "plot.waffleX(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/waffle"
  },
  {
    "namespace": "plot",
    "group": "plot",
    "name": "waffleY",
    "qualified": "plot.waffleY",
    "call": "plot.waffleY(options)",
    "own": [],
    "universal": [
      "channels",
      "id",
      "edits",
      "table"
    ],
    "docs": "/marks/waffle"
  },
  {
    "namespace": "elements",
    "group": "elements",
    "name": "axis",
    "qualified": "elements.axis",
    "call": "elements.axis(options)",
    "own": [
      "channel",
      "anchor",
      "transform",
      "ticks",
      "tickValues",
      "tickFormat",
      "tickSize",
      "title",
      "stroke",
      "fill",
      "fontSize",
      "grid",
      "handleColor",
      "handleSize"
    ],
    "universal": [
      "id",
      "edit",
      "edits",
      "field",
      "table"
    ],
    "docs": "/marks/axes"
  },
  {
    "namespace": "elements",
    "group": "elements",
    "name": "axisRadial",
    "qualified": "elements.axisRadial",
    "call": "elements.axisRadial(options)",
    "own": [
      "channel",
      "channels",
      "radius",
      "innerRadius",
      "bandWidth",
      "ticks",
      "tickValues",
      "tickFormat",
      "tickSize",
      "labelOffset",
      "bands",
      "title",
      "arc",
      "orient",
      "start",
      "end",
      "labelFill",
      "stroke",
      "strokeWidth",
      "fontSize"
    ],
    "universal": [
      "id",
      "edit",
      "edits",
      "field",
      "table"
    ],
    "docs": "/marks/axis-radial"
  },
  {
    "namespace": "elements",
    "group": "elements",
    "name": "axisX",
    "qualified": "elements.axisX",
    "call": "elements.axisX(options)",
    "own": [],
    "universal": [
      "id",
      "edit",
      "edits",
      "field",
      "table"
    ],
    "docs": "/marks/axes"
  },
  {
    "namespace": "elements",
    "group": "elements",
    "name": "axisY",
    "qualified": "elements.axisY",
    "call": "elements.axisY(options)",
    "own": [],
    "universal": [
      "id",
      "edit",
      "edits",
      "field",
      "table"
    ],
    "docs": "/marks/axes"
  },
  {
    "namespace": "elements",
    "group": "elements",
    "name": "grid",
    "qualified": "elements.grid",
    "call": "elements.grid(options)",
    "own": [
      "channel",
      "ticks",
      "tickValues",
      "stroke",
      "strokeWidth"
    ],
    "universal": [
      "id",
      "edit",
      "edits",
      "field",
      "table"
    ],
    "docs": "/marks/axes"
  },
  {
    "namespace": "elements",
    "group": "elements",
    "name": "gridX",
    "qualified": "elements.gridX",
    "call": "elements.gridX(options)",
    "own": [],
    "universal": [
      "id",
      "edit",
      "edits",
      "field",
      "table"
    ],
    "docs": "/marks/axes"
  },
  {
    "namespace": "elements",
    "group": "elements",
    "name": "gridY",
    "qualified": "elements.gridY",
    "call": "elements.gridY(options)",
    "own": [],
    "universal": [
      "id",
      "edit",
      "edits",
      "field",
      "table"
    ],
    "docs": "/marks/axes"
  },
  {
    "namespace": "elements",
    "group": "elements",
    "name": "legend",
    "qualified": "elements.legend",
    "call": "elements.legend(options)",
    "own": [
      "channel",
      "anchor",
      "orient",
      "swatchSize",
      "gap",
      "labelWidth",
      "rampLength",
      "rampThickness",
      "ticks",
      "tickFormat",
      "title",
      "row",
      "stroke",
      "fill",
      "fontSize",
      "handleColor",
      "handleSize"
    ],
    "universal": [
      "id",
      "edit",
      "edits",
      "field",
      "table"
    ],
    "docs": "/marks/legend"
  },
  {
    "namespace": "elements",
    "group": "elements",
    "name": "legendColor",
    "qualified": "elements.legendColor",
    "call": "elements.legendColor(options)",
    "own": [],
    "universal": [
      "id",
      "edit",
      "edits",
      "field",
      "table"
    ],
    "docs": "/marks/legend"
  },
  {
    "namespace": "elements",
    "group": "elements",
    "name": "legendSize",
    "qualified": "elements.legendSize",
    "call": "elements.legendSize(options)",
    "own": [],
    "universal": [
      "id",
      "edit",
      "edits",
      "field",
      "table"
    ],
    "docs": "/marks/legend"
  },
  {
    "namespace": "elements",
    "group": "elements",
    "name": "legendSymbol",
    "qualified": "elements.legendSymbol",
    "call": "elements.legendSymbol(options)",
    "own": [],
    "universal": [
      "id",
      "edit",
      "edits",
      "field",
      "table"
    ],
    "docs": "/marks/legend"
  },
  {
    "namespace": "edit",
    "group": "edit.axis",
    "name": "scale",
    "qualified": "edit.axis.scale",
    "call": "edit.axis.scale(options)",
    "own": [
      "field",
      "mode"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/axis"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "brushRect",
    "qualified": "edit.brushRect",
    "call": "edit.brushRect(options)",
    "own": [
      "edgeInset",
      "resize",
      "move"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/handles"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "brushSpan",
    "qualified": "edit.brushSpan",
    "call": "edit.brushSpan(options)",
    "own": [
      "edgeInset"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/handles"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "create",
    "qualified": "edit.create",
    "call": "edit.create(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/existence"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "custom",
    "qualified": "edit.custom",
    "call": "edit.custom(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/gestures"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "cycle",
    "qualified": "edit.cycle",
    "call": "edit.cycle(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/gestures"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "editText",
    "qualified": "edit.editText",
    "call": "edit.editText(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/marks/sticker"
  },
  {
    "namespace": "edit",
    "group": "edit.geo",
    "name": "brush",
    "qualified": "edit.geo.brush",
    "call": "edit.geo.brush(options)",
    "own": [
      "move",
      "edgeInset"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.geo",
    "name": "create",
    "qualified": "edit.geo.create",
    "call": "edit.geo.create(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.geo",
    "name": "createRect",
    "qualified": "edit.geo.createRect",
    "call": "edit.geo.createRect(options)",
    "own": [
      "width",
      "height",
      "edgeInset"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.geo",
    "name": "dragVertex",
    "qualified": "edit.geo.dragVertex",
    "call": "edit.geo.dragVertex(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.geo",
    "name": "draw",
    "qualified": "edit.geo.draw",
    "call": "edit.geo.draw(options)",
    "own": [
      "minDist"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.geo",
    "name": "move",
    "qualified": "edit.geo.move",
    "call": "edit.geo.move(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.geo",
    "name": "removeVertex",
    "qualified": "edit.geo.removeVertex",
    "call": "edit.geo.removeVertex(options)",
    "own": [
      "min"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.legend",
    "name": "category",
    "qualified": "edit.legend.category",
    "call": "edit.legend.category(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/legend"
  },
  {
    "namespace": "edit",
    "group": "edit.legend",
    "name": "value",
    "qualified": "edit.legend.value",
    "call": "edit.legend.value(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/legend"
  },
  {
    "namespace": "edit",
    "group": "edit.line",
    "name": "anchor",
    "qualified": "edit.line.anchor",
    "call": "edit.line.anchor(options)",
    "own": [
      "series"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/sweep"
  },
  {
    "namespace": "edit",
    "group": "edit.line",
    "name": "draw",
    "qualified": "edit.line.draw",
    "call": "edit.line.draw(options)",
    "own": [
      "along",
      "value",
      "samples",
      "minDist",
      "series"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/sweep"
  },
  {
    "namespace": "edit",
    "group": "edit.line",
    "name": "newSeries",
    "qualified": "edit.line.newSeries",
    "call": "edit.line.newSeries(options)",
    "own": [
      "along",
      "value",
      "samples",
      "series"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/sweep"
  },
  {
    "namespace": "edit",
    "group": "edit.line",
    "name": "removeSeries",
    "qualified": "edit.line.removeSeries",
    "call": "edit.line.removeSeries(options)",
    "own": [
      "series"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/sweep"
  },
  {
    "namespace": "edit",
    "group": "edit.line",
    "name": "sweep",
    "qualified": "edit.line.sweep",
    "call": "edit.line.sweep(options)",
    "own": [
      "mode"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/sweep"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "move",
    "qualified": "edit.move",
    "call": "edit.move(options)",
    "own": [
      "mode"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/gestures"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "moveSpan",
    "qualified": "edit.moveSpan",
    "call": "edit.moveSpan(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/handles"
  },
  {
    "namespace": "edit",
    "group": "edit.network",
    "name": "connect",
    "qualified": "edit.network.connect",
    "call": "edit.network.connect(options)",
    "own": [
      "source",
      "target",
      "selfLoops"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/marks/network"
  },
  {
    "namespace": "edit",
    "group": "edit.network",
    "name": "reverse",
    "qualified": "edit.network.reverse",
    "call": "edit.network.reverse(options)",
    "own": [
      "source",
      "target"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/marks/network"
  },
  {
    "namespace": "edit",
    "group": "edit.network",
    "name": "rewire",
    "qualified": "edit.network.rewire",
    "call": "edit.network.rewire(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/marks/network"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "rank",
    "qualified": "edit.rank",
    "call": "edit.rank(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/gestures"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "remove",
    "qualified": "edit.remove",
    "call": "edit.remove(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/existence"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "resize",
    "qualified": "edit.resize",
    "call": "edit.resize(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/gestures"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "rotate",
    "qualified": "edit.rotate",
    "call": "edit.rotate(options)",
    "own": [
      "relativeTo",
      "pivot",
      "fold"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/gestures"
  },
  {
    "namespace": "edit",
    "group": "edit.scale",
    "name": "categories",
    "qualified": "edit.scale.categories",
    "call": "edit.scale.categories(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/axis"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "select",
    "qualified": "edit.select",
    "call": "edit.select(options)",
    "own": [
      "exclusive",
      "toggle",
      "multi"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/external-controls"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "set",
    "qualified": "edit.set",
    "call": "edit.set(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/external-controls"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "slide",
    "qualified": "edit.slide",
    "call": "edit.slide(options)",
    "own": [
      "axis",
      "increase",
      "extent",
      "mode"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/gestures"
  },
  {
    "namespace": "edit",
    "group": "edit.stack",
    "name": "cut",
    "qualified": "edit.stack.cut",
    "call": "edit.stack.cut(options)",
    "own": [
      "label",
      "categoryField"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/sweep"
  },
  {
    "namespace": "edit",
    "group": "edit.stack",
    "name": "edge",
    "qualified": "edit.stack.edge",
    "call": "edit.stack.edge(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/handles"
  },
  {
    "namespace": "edit",
    "group": "edit.stack",
    "name": "merge",
    "qualified": "edit.stack.merge",
    "call": "edit.stack.merge(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/sweep"
  },
  {
    "namespace": "edit",
    "group": "edit",
    "name": "toggle",
    "qualified": "edit.toggle",
    "call": "edit.toggle(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing/gestures"
  },
  {
    "namespace": "edit",
    "group": "edit.trend",
    "name": "intercept",
    "qualified": "edit.trend.intercept",
    "call": "edit.trend.intercept(options)",
    "own": [
      "anchor",
      "probe"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.trend",
    "name": "interceptSpread",
    "qualified": "edit.trend.interceptSpread",
    "call": "edit.trend.interceptSpread(options)",
    "own": [
      "anchor",
      "probe"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.trend",
    "name": "slope",
    "qualified": "edit.trend.slope",
    "call": "edit.trend.slope(options)",
    "own": [
      "anchor",
      "probe"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.trend",
    "name": "slopeSpread",
    "qualified": "edit.trend.slopeSpread",
    "call": "edit.trend.slopeSpread(options)",
    "own": [
      "anchor",
      "probe"
    ],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.waffle",
    "name": "fill",
    "qualified": "edit.waffle.fill",
    "call": "edit.waffle.fill(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.when",
    "name": "alt",
    "qualified": "edit.when.alt",
    "call": "edit.when.alt(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.when",
    "name": "far",
    "qualified": "edit.when.far",
    "call": "edit.when.far(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.when",
    "name": "modifier",
    "qualified": "edit.when.modifier",
    "call": "edit.when.modifier(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.when",
    "name": "near",
    "qualified": "edit.when.near",
    "call": "edit.when.near(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.when",
    "name": "nearWithin",
    "qualified": "edit.when.nearWithin",
    "call": "edit.when.nearWithin(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.when",
    "name": "noAlt",
    "qualified": "edit.when.noAlt",
    "call": "edit.when.noAlt(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.when",
    "name": "noModifier",
    "qualified": "edit.when.noModifier",
    "call": "edit.when.noModifier(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.when",
    "name": "noShift",
    "qualified": "edit.when.noShift",
    "call": "edit.when.noShift(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "edit",
    "group": "edit.when",
    "name": "shift",
    "qualified": "edit.when.shift",
    "call": "edit.when.shift(options)",
    "own": [],
    "universal": [
      "type",
      "name",
      "gesture",
      "channel",
      "channels",
      "when",
      "pick",
      "threshold",
      "scope",
      "into",
      "constrain",
      "guide",
      "stage",
      "advance",
      "target",
      "cardinality",
      "inverts",
      "table",
      "inline",
      "multiline",
      "defaults",
      "apply"
    ],
    "docs": "/editing"
  },
  {
    "namespace": "constraints",
    "group": "constraints",
    "name": "clamp",
    "qualified": "constraints.clamp",
    "call": "constraints.clamp(options)",
    "own": [
      "min",
      "max",
      "field"
    ],
    "universal": [],
    "docs": "/constraints"
  },
  {
    "namespace": "constraints",
    "group": "constraints",
    "name": "count",
    "qualified": "constraints.count",
    "call": "constraints.count(options)",
    "own": [
      "max",
      "strategy"
    ],
    "universal": [],
    "docs": "/constraints"
  },
  {
    "namespace": "constraints",
    "group": "constraints",
    "name": "custom",
    "qualified": "constraints.custom",
    "call": "constraints.custom(options)",
    "own": [],
    "universal": [],
    "docs": "/constraints"
  },
  {
    "namespace": "constraints",
    "group": "constraints",
    "name": "maintainSum",
    "qualified": "constraints.maintainSum",
    "call": "constraints.maintainSum(options)",
    "own": [
      "total",
      "field",
      "strategy"
    ],
    "universal": [],
    "docs": "/constraints"
  },
  {
    "namespace": "constraints",
    "group": "constraints",
    "name": "monotonic",
    "qualified": "constraints.monotonic",
    "call": "constraints.monotonic(options)",
    "own": [
      "field",
      "along",
      "dir",
      "series"
    ],
    "universal": [],
    "docs": "/constraints"
  },
  {
    "namespace": "constraints",
    "group": "constraints",
    "name": "ordering",
    "qualified": "constraints.ordering",
    "call": "constraints.ordering(options)",
    "own": [
      "field",
      "strategy"
    ],
    "universal": [],
    "docs": "/constraints"
  },
  {
    "namespace": "constraints",
    "group": "constraints",
    "name": "snap",
    "qualified": "constraints.snap",
    "call": "constraints.snap(options)",
    "own": [
      "step",
      "origin",
      "field"
    ],
    "universal": [],
    "docs": "/constraints"
  },
  {
    "namespace": "constraints",
    "group": "constraints",
    "name": "spacing",
    "qualified": "constraints.spacing",
    "call": "constraints.spacing(options)",
    "own": [
      "field",
      "min",
      "series"
    ],
    "universal": [],
    "docs": "/constraints"
  },
  {
    "namespace": "constraints",
    "group": "constraints",
    "name": "unique",
    "qualified": "constraints.unique",
    "call": "constraints.unique(options)",
    "own": [
      "field",
      "max",
      "strategy"
    ],
    "universal": [],
    "docs": "/constraints"
  },
  {
    "namespace": "guides",
    "group": "guides",
    "name": "cellGrid",
    "qualified": "guides.cellGrid",
    "call": "guides.cellGrid(options)",
    "own": [
      "pad"
    ],
    "universal": [
      "id"
    ],
    "docs": "/guides"
  },
  {
    "namespace": "guides",
    "group": "guides",
    "name": "crosshair",
    "qualified": "guides.crosshair",
    "call": "guides.crosshair(options)",
    "own": [
      "x",
      "y"
    ],
    "universal": [
      "id"
    ],
    "docs": "/guides"
  },
  {
    "namespace": "guides",
    "group": "guides",
    "name": "custom",
    "qualified": "guides.custom",
    "call": "guides.custom(options)",
    "own": [],
    "universal": [
      "id"
    ],
    "docs": "/guides"
  },
  {
    "namespace": "guides",
    "group": "guides",
    "name": "optionRings",
    "qualified": "guides.optionRings",
    "call": "guides.optionRings(options)",
    "own": [
      "labelOffset",
      "radius"
    ],
    "universal": [
      "id"
    ],
    "docs": "/guides"
  },
  {
    "namespace": "guides",
    "group": "guides",
    "name": "prompt",
    "qualified": "guides.prompt",
    "call": "guides.prompt(options)",
    "own": [
      "y"
    ],
    "universal": [
      "id"
    ],
    "docs": "/guides"
  },
  {
    "namespace": "guides",
    "group": "guides",
    "name": "proximity",
    "qualified": "guides.proximity",
    "call": "guides.proximity(options)",
    "own": [
      "target",
      "stroke",
      "strokeDasharray",
      "strokeWidth",
      "opacity"
    ],
    "universal": [
      "id"
    ],
    "docs": "/guides"
  },
  {
    "namespace": "guides",
    "group": "guides",
    "name": "region",
    "qualified": "guides.region",
    "call": "guides.region(options)",
    "own": [
      "x",
      "y",
      "fill",
      "opacity",
      "stroke",
      "label"
    ],
    "universal": [
      "id"
    ],
    "docs": "/guides"
  },
  {
    "namespace": "guides",
    "group": "guides",
    "name": "remaining",
    "qualified": "guides.remaining",
    "call": "guides.remaining(options)",
    "own": [
      "field",
      "total",
      "unit",
      "format",
      "anchor",
      "label",
      "fill",
      "fontSize"
    ],
    "universal": [
      "id"
    ],
    "docs": "/guides"
  },
  {
    "namespace": "guides",
    "group": "guides",
    "name": "rule",
    "qualified": "guides.rule",
    "call": "guides.rule(options)",
    "own": [
      "x",
      "y",
      "stroke",
      "strokeDasharray",
      "strokeWidth",
      "opacity",
      "label"
    ],
    "universal": [
      "id"
    ],
    "docs": "/guides"
  },
  {
    "namespace": "guides",
    "group": "guides",
    "name": "sliderTrack",
    "qualified": "guides.sliderTrack",
    "call": "guides.sliderTrack(options)",
    "own": [
      "format"
    ],
    "universal": [
      "id"
    ],
    "docs": "/guides"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "allocation",
    "qualified": "widgets.allocation",
    "call": "widgets.allocation(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "histogram",
    "qualified": "widgets.histogram",
    "call": "widgets.histogram(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "interval",
    "qualified": "widgets.interval",
    "call": "widgets.interval(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "labeledValue",
    "qualified": "widgets.labeledValue",
    "call": "widgets.labeledValue(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "likert",
    "qualified": "widgets.likert",
    "call": "widgets.likert(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "lineCone",
    "qualified": "widgets.lineCone",
    "call": "widgets.lineCone(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "matrix",
    "qualified": "widgets.matrix",
    "call": "widgets.matrix(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "multipleChoice",
    "qualified": "widgets.multipleChoice",
    "call": "widgets.multipleChoice(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "probabilityTokens",
    "qualified": "widgets.probabilityTokens",
    "call": "widgets.probabilityTokens(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "ranking",
    "qualified": "widgets.ranking",
    "call": "widgets.ranking(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "region",
    "qualified": "widgets.region",
    "call": "widgets.region(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "slider",
    "qualified": "widgets.slider",
    "call": "widgets.slider(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "widgets",
    "group": "widgets",
    "name": "thermometer",
    "qualified": "widgets.thermometer",
    "call": "widgets.thermometer(options)",
    "own": [],
    "universal": [],
    "docs": "/widgets"
  },
  {
    "namespace": "format",
    "group": "format",
    "name": "number",
    "qualified": "format.number",
    "call": "format.number(options)",
    "own": [],
    "universal": [],
    "docs": "/scales"
  },
  {
    "namespace": "format",
    "group": "format",
    "name": "percent",
    "qualified": "format.percent",
    "call": "format.percent(options)",
    "own": [],
    "universal": [],
    "docs": "/scales"
  },
  {
    "namespace": "format",
    "group": "format",
    "name": "prefix",
    "qualified": "format.prefix",
    "call": "format.prefix(options)",
    "own": [],
    "universal": [],
    "docs": "/scales"
  },
  {
    "namespace": "format",
    "group": "format",
    "name": "resolveFormat",
    "qualified": "format.resolveFormat",
    "call": "format.resolveFormat(options)",
    "own": [],
    "universal": [],
    "docs": "/scales"
  },
  {
    "namespace": "format",
    "group": "format",
    "name": "si",
    "qualified": "format.si",
    "call": "format.si(options)",
    "own": [],
    "universal": [],
    "docs": "/scales"
  },
  {
    "namespace": "format",
    "group": "format",
    "name": "suffix",
    "qualified": "format.suffix",
    "call": "format.suffix(options)",
    "own": [],
    "universal": [],
    "docs": "/scales"
  },
  {
    "namespace": "format",
    "group": "format",
    "name": "time",
    "qualified": "format.time",
    "call": "format.time(options)",
    "own": [],
    "universal": [],
    "docs": "/scales"
  }
];
